name: test
on:
   push:
     branches:
       - master
       
jobs:
  build:
     runs-on: ubuntu-latest

    #  container:
    #   image: ghcr.io/catthehacker/ubuntu:act-latest

     steps:
       - name: my first step
         uses: actions/checkout@v4

      #  - name: running dockerfile
      #    uses: ./.github/actions

       - name: Build Docker image
         run: docker build -t hello .

       - run: echo "Dockerfile builded done!"

      #  -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

       - name: upload image to docker hub
         uses: docker/login-action@v3
         with:
          username: ${{secrets.username}}
          password: ${{secrets.password}}

       - name: Build and push docker image
         uses: docker/build-push-action@v6
         with: 
          push: ${{github.event_name != 'pull_request'}}
          tags: ${{ secrets.username }}/test:${{ github.sha }}

  deploy:
    needs: [build]
    runs-on: arc-runner-set

    #container:
     #image: ghcr.io/catthehacker/ubuntu:act-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Setup Docker BuildX
      #   id: setup-buildx
      #   uses: docker/setup-buildx-action@v3
      #   with:
      #     install: true
      #     driver-opts: network=host

      - name: set enviroment variables from github secrets
        run: |
          echo "USERNAME=${{secrets.USERNAME}}" >> $GITHUB_ENV
          echo "PASSWORD=${{secrets.PASSWORD}}" >> $GITHUB_ENV

      - name: login docker hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          logout: true

      - name: deploy to k8s
        run: |
          kubectl apply -f ./echo-deployment.yml
