name: test
on:
   push:
     branches:
       - master
jobs:
  build:
     runs-on: self-hostd

     container:
      image: ubuntu-latest

     steps:
       - name: my first step
         uses: actions/checkout@v2

       - name: Say Hello to the World
         run: echo "Hello, World!"

  deploy:
    needs: [build]
    runs-on: self-hostd

    container:
     image: ubuntu-latest

    steps:
      - run: |
          kubectl apply -f ./echo-deployment.yml
