name: test
on:
   push:
     branches:
       - master
jobs:
  build:
     runs-on: self-hostd

     container:
      image: ghcr.io/catthehacker/ubuntu:act-latest

     steps:
       - name: my first step
         uses: actions/checkout@v2

       - name: running dockerfile
         uses: ./github/.actions

       - name: Say Hello to the World
         run: echo "Hello, World!"

  deploy:
    needs: [build]
    runs-on: arc-runner-set

    container:
     image: ghcr.io/catthehacker/ubuntu:act-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: set enviroment variables from github secrets
        run: |
          echo "USERNAME=${{secrets.USERNAME}}" >> $GITHUB_ENV
          echo "PASSWORD=${{secrets.PASSWORD}}" >> $GITHUB_ENV

      - name: login docker hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          logout: true

      - name: deploy to k8s
        run: |
          kubectl apply -f ./echo-deployment.yml
